version: 2

builds:
  -
    env:
      - CGO_ENABLED=0
    binary: kubectl-vault-login
    ldflags: -s -w -X main.version={{ .Version }}
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm

archives:
  -
    builds:
      - kubectl-vault-login
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: "checksums.txt"

brews:
  - name: kubectl-vault-login
    repository:
      owner: FalcoSuessgott
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP }}"
    directory: Formula
    homepage: https://github.com/FalcoSuessgott/kubectl-vault-login
    description: "kubectl-vault-login"
    install: |
      bin.install "kubectl-vault-login"
    test: |
      system "#{bin}/kubectl-vault-login"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - "^test:"
    - "^chore"
    - "merge conflict"
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
