site_name: kubectl-vault-login
site_description: A kubectl plugin for authenticating to Kubernetes using HashiCorp Vaults Kubernetes Secret Engine
site_author: FalcoSuessgott

repo_name: FalcoSuessgott/kubectl-vault-login
repo_url: https://github.com/FalcoSuessgott/kubectl-vault-login

docs_dir: docs/

plugins:
  - search
  - git-authors
  - git-revision-date-localized:
      locale: en
      enable_creation_date: false

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - toc:
      permalink: true
  - markdown_include.include:
        base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - kubectl-vault-login:
    - index.md
    - installation.md
    - usage.md
    - Guides:
      - mode-01.md
      - mode-02.md
      - mode-03.md

theme:
  name: material
  palette:
    - scheme: slate
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.top
    - navigation.expand
    - navigation.footer

extra_css:
  - assets/style.css
