name: E2E Testing

on:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: eLco/setup-vault@v1
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
          cache: false

      - name: Build plugin
        run: go build -o kubectl-vault-login

      - uses: helm/kind-action@v1
        with:
          cluster_name: vault-k8s-secret
          config: scripts/kind-config.yml

      - name: create a SA and token that is used by vault for creating new service account tokens
        run: |
          kubectl apply -f scripts/mode-01

      - name: Configure Vault k8s secret engine
        run: |
          make vault
          K8S_JWT_TOKEN=$(kubectl get secret vault-auth-token -o jsonpath="{.data.token}" | base64 -d)
          K8S_CA_CERT=$(kubectl get secret vault-auth-token -o jsonpath="{['data']['ca\.crt']}" | base64 -d)

          vault secrets enable kubernetes
          vault write -f kubernetes/config \
              kubernetes_host="https://127.0.0.1:6443" \
              kubernetes_ca_cert="$K8S_CA_CERT" \
              service_account_jwt="$K8S_JWT_TOKEN"

          vault write kubernetes/roles/kind \
              allowed_kubernetes_namespaces="default" \
              service_account_name="tmp-sa" \
              token_default_ttl="10m"
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root

      - name: Generate credentials
        run: ./kubectl-vault-login -r kind
        env:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_TOKEN: root
